@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager  " as LogicManager LOGIC_COLOR
participant ":MasterParser " as MasterParser LOGIC_COLOR
participant ":AddCardCommandParser    " as AddCardCommandParser LOGIC_COLOR
participant "r:AddCardCommand    " as AddCardCommand LOGIC_COLOR
participant ":CommandResult   " as CommandResult LOGIC_COLOR
end box


box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add Good Morning: Selamat Pagi")
activate LogicManager

LogicManager -> MasterParser : parseCommand("add Good Morning: Selamat Pagi ")
activate MasterParser

create AddCardCommandParser
MasterParser -> AddCardCommandParser
activate AddCardCommandParser

AddCardCommandParser --> MasterParser
deactivate AddCardCommandParser

MasterParser -> AddCardCommandParser : parse("Good Morning: Selamat Pagi")
activate AddCardCommandParser

create AddCardCommand
AddCardCommandParser -> AddCardCommand
activate AddCardCommand

AddCardCommand --> AddCardCommandParser : r
deactivate AddCardCommand

AddCardCommandParser --> MasterParser : r
deactivate AddCardCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCardCommandParser -[hidden]-> MasterParser
destroy AddCardCommandParser

MasterParser --> LogicManager : r
deactivate MasterParser

LogicManager -> AddCardCommand : execute()
activate AddCardCommand

AddCardCommand -> Model : createCard("Good Morning", "Selamat Pagi")
activate Model

Model --> AddCardCommand
deactivate Model

create CommandResult
AddCardCommand -> CommandResult
activate CommandResult

CommandResult --> AddCardCommand
deactivate CommandResult

AddCardCommand --> LogicManager : result
deactivate AddCardCommand

[<--LogicManager
deactivate LogicManager
@enduml
