@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package "Core"<<Rectangle>>{
    Class Hidden #FFFFFF
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
}

scale 600 width

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1
Class Main MODEL_COLOR_T1

Class Commons LOGIC_COLOR_T2
Class "LogsCenter" as Logs UI_COLOR_T2
Class Index UI_COLOR_T2
Class Messages UI_COLOR_T2
Class Exceptions UI_COLOR_T2

Main -right-> Core

UI -> Logic
UI -right-> Model
Logic -> Storage
Logic -down-> Model

Storage .right.>File
User --> UI

Storage ..down[hidden]> Hidden
Commons -right-> Logs
Commons -down-> Index
Commons -down-> Messages
Commons -down-> Exceptions
Hidden .down.> Commons
@enduml
