@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MasterParser" as MasterParser LOGIC_COLOR
participant ":RemoveDeckCommandParser" as RemoveDeckCommandParser LOGIC_COLOR
participant "r:RemoveDeckCommand" as RemoveDeckCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("remove 2")
activate LogicManager

LogicManager -> MasterParser : parseCommand("remove 2")
activate MasterParser

create RemoveDeckCommandParser
MasterParser -> RemoveDeckCommandParser
activate RemoveDeckCommandParser

RemoveDeckCommandParser --> MasterParser
deactivate RemoveDeckCommandParser

MasterParser -> RemoveDeckCommandParser : parse("2")
activate RemoveDeckCommandParser

create RemoveDeckCommand
RemoveDeckCommandParser -> RemoveDeckCommand
activate RemoveDeckCommand

RemoveDeckCommand --> RemoveDeckCommandParser : r
deactivate RemoveDeckCommand

RemoveDeckCommandParser --> MasterParser : r
deactivate RemoveDeckCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
RemoveDeckCommandParser -[hidden]-> MasterParser
destroy RemoveDeckCommandParser

MasterParser --> LogicManager : r
deactivate MasterParser

LogicManager -> RemoveDeckCommand : execute()
activate RemoveDeckCommand

RemoveDeckCommand -> Model : removeDeck(2)
activate Model

Model --> RemoveDeckCommand
deactivate Model

create CommandResult
RemoveDeckCommand -> CommandResult
activate CommandResult

CommandResult --> RemoveDeckCommand
deactivate CommandResult

RemoveDeckCommand --> LogicManager : result
deactivate RemoveDeckCommand

[<--LogicManager
deactivate LogicManager
@enduml
