@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

package Parser {
Interface Parser <<Interface>>
Class MasterParser
Class *CommandParser
Class ParserUtil
}

package Command {
Class *Command
Class CommandResult
Class "{abstract}\nCommand" as Command
}

Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic
LogicManager -->"1" MasterParser
MasterParser .left.> "*CommandParser": creates >

"*CommandParser" ..> "*Command" : creates >
"*CommandParser" ..|> Parser
"*CommandParser" ..> ParserUtil
"*Command" -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> Model
Command .right.> Model
note right of "*Command": ~*Command: AddCardCommand, \nRemoveDeckCommand, etc.

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult
CommandResult -[hidden]-> Parser
@enduml
