@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyLibrary <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Library
Class ReadOnlyLibrary
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class GameManager
Class Mode
Class View

Class Deck
Class UniqueDeckList
Class UniqueCardList
Class Card


Class HiddenOutside #FFFFFF


Library .up.|> ReadOnlyLibrary

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Library
ModelManager o--> "0..1" GameManager
ModelManager o--> "0..1" Deck
ModelManager o--> "0..1" Card
ModelManager o--> "1" Mode
ModelManager o--> "1" View
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs


Library *--> "1" UniqueDeckList
GameManager *--> "1" UniqueCardList
UniqueDeckList o--> "*" Deck
Deck *--> "1" UniqueCardList
UniqueCardList o--> "*" Card


@enduml
