= Chiew Kok Seng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FlashSpeed

---

== Overview

FlashSpeed is a text-based flashcard application specifically designed for university students
who are learning a foreign language.
University students often have hectic schedules.
With this in mind,
FlashSpeed was created to allow students to be able to study and revise foreign vocabulary on the fly.


== Summary of contributions

* *Major enhancement*: *designed the architecture of the app*.
** What it does: creates the backbone structure of the application.
** Justification: This contribution is critical to the development of the product
because it created the basic structure of the app so that different features could be developed simultaneously.
** Highlights: This contribution sets the tone of the application.
It required an in-depth analysis of how the application should work in the future.
The implementation too was challenging as it required making high-level design choices.
** Credits: Some of the high-level structure of FlashSpeed is inspired by Anki, a digital flashcard application.

* *Major enhancement*: added *the ability to generate statistics after every game session*
** What it does: allows the user to look at the statistics related to the game session that he/she played.
** Justification: This feature increases the usage rate of the app,
because it provides a feedback on the performance of the user.
By quantifying the performance, this gives user motivation to do better in subsequent game sessions, and hence the app
usage time will increase.
** Highlights: This enhancement affects existing commands and commands to be added in future.
It required an in-depth analysis of design alternatives.
The implementation too was challenging as it required changes to existing commands.
** Credits:

* *Major enhancement*: added *the storage function to the app.*
** What it does: allows the user to save and load the decks of cards created by the user to a local directory.
Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the usability of the product significantly
because a user needs to be able to retrieve the decks of cards that he/she has created in the past.
** Highlights: This enhancement affects existing commands and commands to be added in future.
It required an in-depth analysis of design alternatives.
The implementation too was challenging as it required changes to existing commands.
** Credits:

* *Minor enhancement*: added a clear deck command that allows the user to delete the

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_