= Pham Tran Tuan Linh - lacedaemon98 - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FlashSpeed

---

== Overview

FlashSpeed is a text-based flashcard application specifically designed for university students who are learning a foreign language. University students often have hectic schedules. With this in mind, FlashSpeed was created to allow students to be able to study and revise foreign vocabulary on the fly. With a single command, you can start a quick study session on FlashSpeed whenever!

Keeping, flipping, and tracking physical flashcards can be a pain. FlashSpeed enhances the studying process by having virtual flashcards and a smarter review system. Users will be tested more frequently on flashcards that they had trouble memorizing previously.

By using FlashSpeed, you will learn faster and remember for longer!

== Summary of contributions

* *Major enhancement*: Develop everything related to User Interface (UI): colour scheme, displaying contents, placement of contents.
** What it does: Allows the user to view and interact with the application
** Justification: This component is crucial to the application because it visualises the whole application in order for it to function.
** Highlights: This component requires a lot of planning and in-depth analysis to the behaviours of all existing and future features. E.g: When and how the scenes should be switched?; When the user updates a content, how to show the updated content immediately?
** Credits: address-book-level3

* *Minor enhancement*: designed the application logo, contributed to the logic of other commands such as `select`, `play`, etc.

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=lacedaemon98&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Functional & Test code]]

* *Other contributions*:

** Project management:
*** Initiate discussions outside meetings.
*** Actively try to spot bugs and report/fix them.
** Enhancements to existing features:
*** Display help without Internet connection needed: Show the User Guide directly when using `help` instead of just showing the link (Pull requests https://github.com/AY1920S2-CS2103T-W17-1/main/pull/194[#194], https://github.com/AY1920S2-CS2103T-W17-1/main/pull/195[#195])
*** Spot and fix bugs in other features such as `reset`, `stop`, `exit`, etc. (Pull requests https://github.com/AY1920S2-CS2103T-W17-1/main/pull/271[#271], https://github.com/AY1920S2-CS2103T-W17-1/main/pull/175[#175], https://github.com/AY1920S2-CS2103T-W17-1/main/pull/193[#193])
** Documentation:
*** Provide all the product screenshots in the User Guide and Developer Guide and update them when there are changes to the application

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=selectDeck]

// include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=selecting-a-deck]

// include::../DeveloperGuide.adoc[tag=dataencryption]


