= FlashSpeed - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S2-CS2103T-W17-1/main

By: `FlashSpeed Foundation`      Since: `Feb 2020`      Licence: `MIT`

== Introduction

FlashSpeed is a text-based flashcard application specifically designed for university students who are learning a foreign language. University students often have hectic schedules. With this in mind, FlashSpeed was created to allow students to be able to study and revise foreign vocabulary on the fly. With a single command, you can start a quick study session on FlashSpeed whenever!

FlashSpeed enhances the revision process by adopting the Space Repetition System (SRS) in its design. Users will be tested more frequently on new words, or words that they have gotten wrong in previous sessions. This system benefits from the psychological spacing effect. SRS has been scientifically proven to increase the rate of learning and memorisation [1]. By using FlashSpeed, you will learn faster and remember for longer!

We hope you enjoy using our app. Happy FlashSpeeding!


== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `flashspeed.jar` link:https://github.com/AY1920S2-CS2103T-W17-1/main/releases[here].
.  Copy the file to the folder you want to use as the home folder for FlashSpeed.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* **`create`**`Japanese 1` : creates a deck named `Japanese 1` in the library
* **`remove`**`3` : removes the 3rd deck shown in the decks list
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `<>` are the parameters to be supplied by the user. +
e.g. in `create <deck>`, `<deck>` is a parameter which can be used as `create Japanese 1`.
====

====
*Different Views*

FlashSpeed can be in one of 3 different views, namely:

* Library view: when no deck is selected and no cards are shown
* Deck view: when a deck has been selected and its cards are shown
* Play view: when in a study session of a deck

Note that some commands may only be valid in certain views.
====

=== General

==== Viewing help : `help`

You can get the link to this this user guide in a new window by typing `help`
in the command line and hit Enter. +
Format: `help`

==== Exiting the program : `exit`

You can exit FlashSpeed just by typing `exit` in the command line and hit Enter. +
Format: `exit`

==== Resetting the library : `reset`

If you want to delete everything in the library start start afresh,
you can choose to reset the library.
You can do so by typing typing `reset` in the command line and hit Enter. +
Format: `reset`

=== Library view

[[selectDeck]]
==== Selecting a deck : `select`

If you want to view the cards in a particular deck or make some changes to it, you can use the
`select` keyword. After selecting a certain deck, Flashspeed will enter the Deck View, and
the right panel of Flashspeed will show all the cards in the deck. +

In Deck View, you can use any of the Deck mode commands listed in <<deckViewAnchor, 3.3>>.

Format: `select <index>`

****
* *Formal definition*:
Selects and shows all cards in the deck at the specified `index`.
The index refers to the index number shown in the displayed decks list. The index *must be a positive integer* 1, 2, 3, ...
****

Example:

* `select 2` +
Selects and shows all cards in the 2nd deck.

==== Creating a deck : `create`

You can creates a new deck in the library just by using this `create` command.
Note that you can use this commmand in both Deck View and Library View.+

Format: `create <deck>`

Examples:

* `create Japanese 1`
* `create Japanese Verbs`

==== Removing a deck : `remove`

Similarly, you can remove a deck in the library by using the `remove` command.

Format: `remove <index>`

****
* *Formal definition*: Removes the deck in the library at the specified `index`.
The index refers to the index number shown in the displayed decks list.
The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `remove 2` +
Removes the 2nd deck from the library.

==== Renaming a deck : `rename`

You can remove a deck in the library by using the `remove` command. Note that the the name of the deck cannot be empty.
Format: `rename <index> <deck>`

****
* Renames the deck in the library at the specified `index`. The index refers to the index number shown in the displayed decks list. The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `rename 2 Japanese Verbs` +
Renames the 2nd deck in the library to "Japanese Verbs".

==== Playing a deck : `play`

Here comes the single most important command in FlashSpeed. In order to start playing with a certain deck,
you can use the `play` command to start a game session with a deck. We "play" it because learning can be fun! +

Format: `play <index>`

****
* *Formal definition*: Starts a game session with the deck in the library at the specified `index`. The index refers to the index number shown in the displayed decks list. The index *must be a positive integer* 1, 2, 3, ...
****

Example:

* `play 2` +
Starts a game session with the 2nd deck in the library.

[[deckViewAnchor]]
=== Deck view

**Important: All commands in this section can only be used in Deck View.**
**To enter Deck View, you must <<selectDeck,select a deck>>.**

==== Adding a card : `add`

You can add a new card to the selected deck by using the `add` command. +

Format: `add <front>:<back>`

Examples:

* `add ありがとう:thanks`
* `add いい[お]てんきですね。:Nice weather, isn't it?`

==== Editing a card : `edit`

You can edit the front and/or back values of any cards in the current deck. +

Format 1: `edit <index> <front>:<back>` +
Format 2: `edit <index> :<back>` +
Format 3: `edit <index> <front>:`

Note that you don't have to supply both front and back values of a card,
ie if you only wish to change the back of a card, the front cant be left blank, vice versa.

****
* Edits the card in the current deck at the specified `index`. The index refers to the index number shown in the displayed cards list. The index *must be a positive integer* 1, 2, 3, ...
* Existing values will be updated to the given values.
* Empty values for the `front` or `back` will leave the associated values intact.
****

Examples:

* `edit 1 ありがとう:thanks` +
Edits the front and back values of the 1st card in the deck to be `ありがとう` and `thanks` respectively.
* `edit 1 :thanks` +
Edits the back value of the 1st card in the deck to be `thanks`.
* `edit 1 ありがとう:` +
Edits the front value of the 1st card in the deck to be `ありがとう`.

==== Deleting a card : `delete`

You can delete a card from the current deck by using the `delete` command. +

Format: `delete <index>`

****
* Deletes the card in the current deck at the specified `index`. The index refers to the index number shown in the displayed cards list. The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `delete 2` +
Deletes the 2nd card in the current deck.

==== Returning to the library : `return`

Once you're done modifying the selected deck,
you can return back to the library with the `return` command, i.e. no deck will be selected. +

Format: `return`

=== Play view

==== Flipping a card : `flip`

To flip a card in Play View and get the back of a card, simply type `flip` into the command line
and hit Enter.+

Format: `flip`

==== Answering "yes" : `yes`

If you could remember the back face of a card, type `yes` into the command line and hit Enter.
You can only do this after flipping the card. +

Format: `yes`

==== Answering "no" : `no`
On the other hand, if you could not remember the back face of a card, type `no` into the command line and hit Enter.
You can only do this after flipping the card. +

Format: `no`

=== Saving the data

All data in FlashSpeed (e.g. decks, cards) are saved in the hard disk automatically after any command that changes the data. +
You dont have to save your decks and cards manually!

== FAQ

*Q*: How do I transfer my data to another computer? +
*A*: Install FlashSpeed in the other computer and overwrite the data folder it creates with your current data folder.

== Command Summary

* *Help* : `help` +
* *Exit* : `exit` +
* *Reset* : `reset`

* *Select* : `select <index>` +
e.g. `select 2`
* *Create* : `create <deck>` +
e.g. `create Japanese 1`
* *Remove* : `remove <index>` +
e.g. `remove 2`
* *Rename* : `rename <index> <deck>` +
e.g. `rename 2 Japanese Verbs`
* *Play* : `play <index>` +
e.g. `play 2`

* *Add* `add <front>:<back>` +
e.g. `add ありがとう:thanks`
* *Edit* : `edit <index> <front>:<back>` or `edit <index> :<back>` or `edit <index> <front>:` +
e.g. `edit 1 ありがとう:thanks` or `edit 1 :thanks` or `edit 1 ありがとう:`
* *Delete* : `delete <index>` +
e.g. `delete 3`
* *Return* : `return`

* *Flip* : `flip`
* *Yes* : `yes`
* *No* : `no`
